version: '2'
services:
  mysql:
    container_name: mysql
    # image: mysql:5.5
    image: mysql:5.6.38
    privileged: true
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "/usr/local/lib/mysql/:/var/lib/mysql/"
      - "./data/mysql/:/etc/mysql/conf.d/"
      # - "./data/mysql/my.cnf:/usr/my.cnf"
      # - "./data/mysql/my.cnf:/etc/mysql/my.cnf"
    env_file:
      - ./.ENV
      # - /etc/profile.d/env_docker
    networks:
          - myapp
networks:
  myapp:
    driver: bridge