version: '2'
services:
  php:
    build: data/php-bio
    image: php:7.0
    ports:
      - "9000:9000"
    links:
      - mysql
    privileged: true
    volumes:
      - /var/www/:/var/www/
    tty: true
    env_file:
      - variables.env
    networks:
      - myapp
  composer:
    privileged: true
    image: composer:1.3
    links:
      - php
    volumes_from:
      - php
    working_dir: /composer
    volumes:
      - /var/www/:/var/www/
      - /usr/lib/composer/:/composer
    env_file:
      - variables.env
    networks:
      - myapp
  web:
    restart: always
    build: data/nginx
    image: nginx
    ports:
      - "80:80"
    links:
      - php
      - mysql
    privileged: true
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/:/var/www/
      - ./data/log/nginx:/var/log/nginx
    env_file:
      - variables.env
    networks:
      - myapp
  mysql:
    container_name: mysql
    image: mysql:5.6
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/lib/mysql/:/var/lib/mysql
      - ./data/mysql/:/etc/mysql/conf.d/
    env_file:
      - ./.ENV
      # - variables.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: sqlmestre
    #   MYSQL_DATABASE: root
    #   MYSQL_USER: maycon
    #   MYSQL_PASSWORD: sqlmestre
    networks:
      - myapp
networks:
  myapp:
    driver: bridge

