version: '2'
services:
  php:
    build: data/php-5.6
    image: php:5.6
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - ${ENVIRONMENT_PATH}:/var/www/
      - /var/lib/jenkins:/var/jenkins_home
    tty: true
  web:
    build: data/nginx
    image: nginx:1.10.2
    ports:
      - "80:80"
    links:
      - php
    privileged: true
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${ENVIRONMENT_PATH}:/var/www/
      - ./data/log/nginx:/var/log/nginx
  mysql:
    image: mysql:5.6
    privileged: true
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - variables.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # composer:
  #   privileged: true
  #   image: composer:1.3
  #   links:
  #     - php
  #   volumes_from:
  #     - php
  #   working_dir: /composer
  #   volumes:
  #     - /var/www/:/var/www/
  #     - /usr/lib/composer/:/composer
  # ci:
  #   build: data/jenkins
  #   image: jenkins
  #   ports:
  #     - "8081:8080"
  #     - "50001:50000"
  #   # environment:
  #     # - JAVA_OPTS="java.util.logging.config.file=/var/jenkins_home/log.properties"
  #   volumes:
  #     - /var/lib/jenkins:/var/jenkins_home
